spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/oauth2_database
        username: root
        password: password1$
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
